apps/students/urls.py
from django.urls import path

from .views import (
    DownloadCSVViewdownloadcsv,
    StudentBulkUploadView,
    StudentCreateView,
    StudentDeleteView,
    StudentDetailView,
    StudentListView,
    StudentUpdateView,
    FeedbackListView,
    SendNotificationView
)

urlpatterns = [
    path("list", StudentListView.as_view(), name="student-list"),
    path("<int:pk>/", StudentDetailView.as_view(), name="student-detail"),
    path("create/", StudentCreateView.as_view(), name="student-create"),
    path("<int:pk>/update/", StudentUpdateView.as_view(), name="student-update"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="student-delete"),
    path("upload/", StudentBulkUploadView.as_view(), name="student-upload"),
    path("download-csv/", DownloadCSVViewdownloadcsv.as_view(), name="download-csv"),
    path('feedback/', FeedbackListView.as_view(), name='feedback-list'),
    path('communication/',  SendNotificationView.as_view(), name='send-notification'),
]

school_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

admin.site.site_header = 'SchooBee Admin Panel'
admin.site.site_title = 'SchooBee'
admin.site.index_title = 'Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("apps.base.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
    path("api/", include("apps.api.urls")),
    path("attendance/", include("apps.attendance.urls")),
    path('timetable/', include('apps.time_table.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.base.views.error_404_view'

apps/students/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone

from apps.corecode.models import StudentClass, AcademicSession, AcademicTerm
from django.contrib.auth import get_user_model

CustomUser = get_user_model()

class Student(models.Model):
    STATUS_CHOICES = [("active", "Active"), ("inactive", "Inactive")]

    GENDER_CHOICES = [("male", "Male"), ("female", "Female")]

    current_status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="active")
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    registration_number = models.CharField(max_length=200, unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    guardian_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default="male")
    date_of_birth = models.DateField(default=timezone.now)
    current_class = models.ForeignKey(
        StudentClass, on_delete=models.SET_NULL, blank=True, null=True
    )
    date_of_admission = models.DateField(default=timezone.now)

    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    parent_mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13
    )

    address = models.TextField()
    comments = models.TextField(blank=True)
    passport = models.ImageField(blank=True, upload_to="students/passports/")
    session = models.ForeignKey(AcademicSession, on_delete=models.CASCADE)
    term = models.ForeignKey(AcademicTerm, on_delete=models.CASCADE)

    class Meta:
        ordering = ["registration_number", "first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.registration_number})"

    def get_absolute_url(self):
        return reverse("student-detail", kwargs={"pk": self.pk})

class StudentBulkUpload(models.Model):
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    date_uploaded = models.DateTimeField(auto_now=True)
    csv_file = models.FileField(upload_to="students/bulkupload/")

class Feedback(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

class Notification(models.Model):
    RECIPIENT_CHOICES = [
        ('student', 'Student'),
        ('class', 'Class'),
        ('school', 'School'),
    ]

    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sent_notifications')
    person_mail = models.CharField(max_length=200, null=True, blank=True)
    title = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    recipients = models.CharField(max_length=10, choices=RECIPIENT_CHOICES)
    class_for = models.ForeignKey(StudentClass, on_delete=models.CASCADE, null=True, blank=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

apps/students/views.py
import csv
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import widgets
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe
from apps.finance.models import Invoice
from .models import Student, StudentBulkUpload, Feedback, Notification, AcademicSession, AcademicTerm
from apps.staffs.models import Staff
from apps.result.models import Result
from apps.corecode.models import StudentClass
from plotly.offline import plot
import plotly.express as px 
import pandas as pd
from django.core.exceptions import ValidationError
from django.contrib import messages
from io import StringIO

class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "students/student_list.html"
    context_object_name = "students"
    
    def get_queryset(self):
        finaluser = self.request.user
        if finaluser.is_faculty:
            staffrecord = Staff.objects.get(email=finaluser.username)
            finaluser = staffrecord.user
        queryset = super().get_queryset()
        current_session = AcademicSession.objects.filter(user=finaluser, current=True).first()
        current_term = AcademicTerm.objects.filter(user=finaluser, current=True,).first()

        return queryset.filter(user=finaluser,session=current_session, term=current_term)

class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    template_name = "students/student_detail.html"

    def get_context_data(self, **kwargs):
        finaluser = self.request.user
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        if finaluser.is_faculty:
            staffrecord = Staff.objects.get(email=finaluser.username)
            finaluser = staffrecord.user
            payments = None
        else:
            payments = Invoice.objects.filter(student=self.object)
        context["payments"] = payments
        results = Result.objects.filter(user=finaluser, student=self.object)
        subjects, subject, marks = dict(), list(), list()
        score, total = 0, 0
        for result in results:
            exam = result.exam_score
            total += exam
            subjects[str(result.subject)] = {"exam": exam, "score": score}

            subject.append(str(result.subject))
            marks.append(score)

        if len(results) > 0:
            percentage = round((total / (len(results) * 100)) * 100)
        else:
            percentage = 0

        df = pd.DataFrame(marks, subject)
        fig = px.bar(df, color=subject)
        fig.update_traces(width=0.5)
        chart = plot(fig, output_type="div")

        context["result"] = subjects
        context["total"] = total
        context["percentage"] = percentage
        context["chart"] = chart
        return context

class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Student
    fields = ['current_status', 'registration_number', 'first_name', 'last_name', 'guardian_name', 'gender',
              'date_of_birth', 'current_class', 'date_of_admission', 'parent_mobile_number', 'address', 'comments',
              'passport']
    success_url = reverse_lazy("student-list")  # Redirect URL after successful form submission

    def get_form(self, form_class=None):
        finaluser = self.request.user
        if finaluser.is_faculty:
            staffrecord = Staff.objects.get(email=finaluser.username)
            finaluser = staffrecord.user

        """Add date picker in forms"""
        form = super().get_form(form_class)
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        form.fields["comments"].widget = widgets.Textarea(attrs={"rows": 2})
        # Setting the queryset for the current_class field
        form.fields["current_class"].queryset = StudentClass.objects.filter(user=finaluser)

        # Adding a link to create a class in the help text
        form.fields["current_class"].help_text = mark_safe(
            '<a href="{}">Click here to add class</a>'.format(reverse_lazy('class-create')))
        form.fields["current_class"].empty_label = "Select One Class"
        return form

    def form_valid(self, form):
        finaluser = self.request.user
        if finaluser.is_faculty:
            staffrecord = Staff.objects.get(email=finaluser.username)
            finaluser = staffrecord.user

        form.instance.user = finaluser  # Assign the logged-in user to the student's user field
        current_session = AcademicSession.objects.filter(user=finaluser, current=True).first()
        current_term = AcademicTerm.objects.filter(user=finaluser, current=True).first()

        if current_session is None or current_term is None:
            messages.error(self.request,
                           "Sessions or terms are empty. Please create sessions and terms before creating a student.")
            return self.form_invalid(form)

        form.instance.session = current_session  # Assign the current session to the student's session field
        form.instance.term = current_term  # Assign the current term to the student's term field

        return super().form_valid(form)

class StudentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Student
    fields = ['current_status','registration_number', 'first_name', 'last_name', 'guardian_name', 'gender', 'date_of_birth', 'current_class', 'date_of_admission', 'parent_mobile_number', 'address', 'comments', 'passport']
    success_message = "Record successfully updated."

    def get_form(self):
        """add date picker in forms"""
        form = super(StudentUpdateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(
            attrs={"type": "date"}
        )
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        form.fields["comments"].widget = widgets.Textarea(attrs={"rows": 2})
        # form.fields['passport'].widget = widgets.FileInput()
        return form
    

    def get_queryset(self):
        finaluser = self.request.user
        if finaluser.is_faculty:
            staffrecord = Staff.objects.get(email=finaluser.username)
            finaluser = staffrecord.user
        queryset = super().get_queryset()
        return queryset.filter(user=finaluser)

    def get_object(self, queryset=None):
        """Retrieve the object to be updated."""
        pk = self.kwargs.get('pk')
        queryset = self.get_queryset()
        obj = queryset.filter(pk=pk).first()
        return obj

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object is None:
            return HttpResponse("No student found matching the query")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy("student-list")

class StudentBulkUploadView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = StudentBulkUpload
    template_name = "students/students_upload.html"
    fields = ["csv_file"]
    success_url = "/student/list"
    success_message = "Successfully uploaded students"
    expected_fields = [
        "registration_number",
        "first_name",
        "last_name",
        "guardian_name",
        "gender",
        "parent_mobile_number",
        "address",
        "current_class",
        "comments"
    ]

    def form_valid(self, form):
        form.instance.user = self.request.user
        # Retrieving the uploaded file
        csv_file = form.cleaned_data.get("csv_file")
        try:
            # Reading the CSV file
            opened = StringIO(csv_file.read().decode())
            reader = csv.DictReader(opened, delimiter=",")
            # Checking if the CSV file contains all the expected fields
            csv_fields = reader.fieldnames
            if not all(field in csv_fields for field in self.expected_fields):
                raise ValidationError("The uploaded CSV file is missing some fields.")
            # Performing further processing and saving
        except csv.Error:
            form.add_error(None, "Invalid CSV file format.")
            return self.form_invalid(form)

        return super().form_valid(form)

    def form_invalid(self, form):
        if form.errors.get("__all__") == ["Invalid CSV file format."]:
            messages.error(self.request, "Invalid CSV file format.")
        else:
            messages.error(self.request, "Something went wrong. Please try again")

        return super().form_invalid(form)

class DownloadCSVViewdownloadcsv(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="student_template.csv"'

        writer = csv.writer(response)
        writer.writerow(
            [
                "registration_number",
                "first_name",
                "last_name",
                "guardian_name",
                "gender",
                "parent_mobile_number",
                "address",
                "current_class",
                "comments"
            ]
        )

        return response

class FeedbackListView(LoginRequiredMixin, ListView):
    model = Feedback
    template_name = 'students/student_feedbacks.html'

apps/students/templates/students/send_notification.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h1>Send Notification</h1>
        </div>
        <div class="card-body">
          <form method="post" id="sendNotificationForm">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_title" class="font-weight-bold">Title:</label>
              <input type="text" name="title" id="id_title" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="id_message" class="font-weight-bold">Message:</label>
              <textarea name="message" id="id_message" rows="3" class="form-control" required></textarea>
            </div>
            <div class="form-group">
              <label for="id_recipients" class="font-weight-bold">Recipient Type:</label>
              <select name="recipients" id="id_recipients" class="form-control" required>
                <option value="student">Student</option>
                <option value="class">Class</option>
                <option value="school">School</option>
              </select>
            </div>
            <div class="form-group" id="studentField" style="display: block;">
              <label for="id_student" class="font-weight-bold">Select Student:</label>
              <select name="student" id="id_student" class="form-control">
                <option value="" selected>Select Student</option>
                {% for student in form.fields.student.queryset %}
                  <option value="{{ student.id }}">{{ student.last_name }} {{ student.first_name }} ({{student.registration_number}})</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group" id="classField" style="display: none;">
              <label for="id_class_for" class="font-weight-bold">Select Class:</label>
              <select name="class_for" id="id_class_for" class="form-control">
                <option value="" selected>Select Class</option>
                {% for class in form.fields.class_for.queryset %}
                  <option value="{{ class.id }}">{{ class.name }}</option>
                {% endfor %}
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Send</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById('id_recipients').addEventListener('change', function() {
    var selectedRecipient = this.value;
    var studentField = document.getElementById('studentField');
    var classField = document.getElementById('classField');

    if (selectedRecipient === 'student') {
      studentField.style.display = 'block';
      classField.style.display = 'none';
    } else if (selectedRecipient === 'class') {
      studentField.style.display = 'none';
      classField.style.display = 'block';
    } else {
      studentField.style.display = 'none';
      classField.style.display = 'none';
    }
  });
</script>
{% endblock %}

apps/students/templates/students/student_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this student will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

apps/students/templates/students/student_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <button class="btn btn-tool" onclick="printData()">Print</button>
    <a href="{% url 'student-update' object.pk %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'student-delete' object.pk %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
<div class="row mb-4">
  <div class="col-sm-4">
    <div class="row mb-2">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'corecode/form_snippet.html' %}
        <input id="passport-input" type="file" name="passport" style="display: none;">
        {% if object.passport %}
        <img id="passport-image" src="{{ object.passport.url }}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
        {% else %}
        {% if object.gender == "female" %}
        <img id="passport-image-gender1" src="{% static 'dist/img/avatar3.png' %}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
        {% else %}
        <img id="passport-image-gender2" src="{% static 'dist/img/avatar5.png' %}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
        {% endif %}
        {% endif %}
      </form>
      <div class="float-right">
        <h4>{{ object.last_name }} </h4>
        <h4>{{ object.first_name }} </h4>
        <h4>{{ object.registration_number }} </h4>
      </div>
    </div>
    <h5>{{ object.current_class }} </h5>
    <h5>{{ object.get_gender_display }} | {{ object.get_current_status_display }}</h5>
  </div>
  <div class="col-sm-8">
    <div>
      <div class="form-group border-bottom row">
        <label class="col">
          Date of Birth
        </label>
        <div class="col">
          {{ object.date_of_birth }}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Date of Admission
        </label>
        <div class="col">
          {{ object.date_of_admission }}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Parent Name
        </label>
        <div class="col">
          {{ object.guardian_name }}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Parent Mobile Number
        </label>
        <div class="col">
          {{ object.parent_mobile_number}}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Address
        </label>
        <div class="col">
          {{ object.address }}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Comments
        </label>
        <div class="col">
          {{ object.comments }}
        </div>
      </div>
    </div>
  </div>
</div>

{% if not user.is_faculty %}
<h4>Invoice/Payment History</h4>
{% if payments %}
<table class="table table-sm table-bordered table-hover">
  <thead class="thead-light">
    <tr>
      <th>For</th>
      <th>Amount Payable</th>
      <th>Amount Paid</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    {% for payment in payments %}
    <tr class='clickable-row' data-href="{% url 'invoice-detail' payment.id %}">
      <td>{{payment.session}} - {{payment.term}} - {{ payment.class_for}}</td>
      <td>{{payment.total_amount_payable}}</td>
      <td>{{payment.total_amount_paid}}</td>
      <td>{{payment.balance}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>There are no payment history for {{ object }}</p>
{% endif %}
{% endif %}

{% if result %}
<div class="card">
  <div class="card-header">
    <h4>Score Card </h4>
  </div>
  <div class="card-body">
    <table class="table table-bordered table-sm">
      <thead class="thead-light">
        <tr>
          <th></th>
          <th>Subject</th>
          <th>Exam Score</th>
        </tr>
      </thead>
      <tbody>
        {% for subject, data in result.items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ subject }}</td>
          <td>{{ data.exam }}</td>
        </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td></td>
          <td colspan="1"><h5>Total Score</h5></td>
          <td><h5>{{ total }}</h5></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td colspan="1"><h5>Percentage</h5></td>
          <td><h5>{{ percentage }} %</h5></td>
          <td></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
{% endif %}

<script>
  // Function to print the content
  function printData() {
    window.print();
  }
</script>
{% endblock content %}

apps/students/templates/students/student_feedbacks.html
{% extends 'base.html' %}

{% block title %}Students Feedbacks{% endblock title %}

{% block content %}
    <ul>
        {% for feedback in feedbacks %}
            <li>
                <strong>Created at: {{ feedback.created_at }}</strong>
                <p>{{ feedback.content }}</p>
            </li>
        {% empty %}
            <li>No feedbacks available.</li>
        {% endfor %}
    </ul>
{% endblock content %}

apps/students/templates/students/student_form.html
{% extends 'base.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new student
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new student">
  {% endif %}
</form>


{% endblock content %}

apps/students/templates/students/student_list.html
{% extends 'base.html' %}

{% block title %}Students{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'student-create' %}"><i
    class="fas fa-plus"></i> New student</a>
<a class="btn btn-primary" href="{% url 'student-upload' %}"><i
    class="fas fa-upload"></i> Upload students</a>
{% endblock breadcrumb %}

{% block content %}
  <div>
    <p style="color: #999999;text-align:right;">Find what you're looking for</p>
  </div>
  <div class="table-responsive">
    <table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0"
    width="100%">
    <thead>
        <tr>
          <th class="th-sm">S/N</th>
          <th class="th-sm">Registration Number</th>
          <th class="th-sm">Fullname</th>
          <th class="th-sm">Guardian Name</th>
          <th class="th-sm">Current Class</th>
          <th class="th-sm">Gender</th>
          <th class="th-sm">Mobile Phone Number</th>
          <th class="th-sm">Status</th>
        </tr>
      </thead>
      <tbody>

        {% for student in students %}
          <tr class='clickable-row' data-href="{% url 'student-detail' student.pk %}">
            <td>{{ forloop.counter}}</td>
            <td>{{ student.registration_number}}</td>
            <td>{{student.first_name }} {{ student.last_name}}</td>
            <td>{{ student.guardian_name }}</td>
            <td>{{ student.current_class}}</td>
            <td>{{ student.get_gender_display}}</td>
            <td>{{ student.parent_mobile_number}}</td>
            <td>{{ student.get_current_status_display}}</td>
          </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
{% endblock content %}


{% block morejs %}
 <script>
  $('#studenttable').DataTable({
  });

  $(document).ready(function () {
  $('#dtDynamicVerticalScrollExample').DataTable({
    "scrollY": "50vh",
    "scrollCollapse": true,
  });
  $('.dataTables_length').addClass('bs-select');
});
</script>

{% endblock morejs %}

apps/students/templates/students/students_upload.html
{% extends 'base.html' %}


{% block title %}
  Upload Bulk Students from file
{% endblock title %}


{% block content %}

  <div class="col alert alert-info">
    <h5>Instruction</h5>
    <p>Please <a href="{% url 'download-csv' %}">download the CSV file attached here</a>. Fill in the sheet and upload the same file back to this page. DO NOT EDIT THE FIRST ROW</p>
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'corecode/form_snippet.html' %}

    <input type="submit" class="btn btn-success" value="Submit">
  </form>

{% endblock content %}