apps/staffs/urls.py
from django.urls import path

from .views import (
    StaffCreateView,
    StaffDeleteView,
    StaffDetailView,
    StaffListView,
    StaffUpdateView,
)

urlpatterns = [
    path("list/", StaffListView.as_view(), name="staff-list"),
    path("<int:pk>/", StaffDetailView.as_view(), name="staff-detail"),
    path("create/", StaffCreateView.as_view(), name="staff-create"),
    path("<int:pk>/update/", StaffUpdateView.as_view(), name="staff-update"),
    path("<int:pk>/delete/", StaffDeleteView.as_view(), name="staff-delete"),
]

school_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

admin.site.site_header = 'SchooBee Admin Panel'
admin.site.site_title = 'SchooBee'
admin.site.index_title = 'Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("apps.base.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
    path("api/", include("apps.api.urls")),
    path("attendance/", include("apps.attendance.urls")),
    path('timetable/', include('apps.time_table.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.base.views.error_404_view'

apps/staffs/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model

CustomUser = get_user_model()

class Staff(models.Model):
    STATUS_CHOICES = [("active", "Active"), ("inactive", "Inactive")]

    GENDER_CHOICES = [("male", "Male"), ("female", "Female")]

    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    email = models.EmailField()
    temp_password = models.CharField(max_length=200)
    current_status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="active")
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default="male")
    date_of_birth = models.DateField(default=timezone.now)

    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13
    )

    address = models.TextField()
    comments = models.TextField(blank=True)
    passport = models.ImageField(blank=True, upload_to="staff/passports/")

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("staff-detail", kwargs={"pk": self.pk})

apps/staffs/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import widgets
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from apps.base.models import CustomUser
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Staff
from django.shortcuts import redirect

class StaffListView(LoginRequiredMixin, ListView):
    model = Staff

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            if self.request.user.is_faculty:
                messages.warning(self.request, "You don't have access to this page")
                return redirect('home')  # Replace 'home' with the appropriate URL name for your home page
        else:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

class StaffDetailView(LoginRequiredMixin, DetailView):
    model = Staff
    template_name = "staffs/staff_detail.html"

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            if self.request.user.is_faculty:
                messages.warning(self.request, "You don't have access to this page")
                return redirect('home')  # Replace 'home' with the appropriate URL name for your home page
        else:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

class StaffCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Staff
    fields = ['current_status','first_name','last_name','gender','date_of_birth','email','mobile_number','address','comments','passport']
    success_message = "New staff successfully added"

    def get_form(self):
        """add date picker in forms"""
        form = super(StaffCreateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 1})
        form.fields["comments"].widget = widgets.Textarea(attrs={"rows": 1})
        form.fields["mobile_number"].widget.attrs["maxlength"] = 10
        return form

    def form_valid(self, form):
        # Create the User object with a random password
        email = form.cleaned_data['email']
        # Check if the username (email) already exists
        if CustomUser.objects.filter(username=email).exists():
            messages.error(self.request, 'This email already exists. Please check if the staff details were not removed by their previous employer.')
            return self.form_invalid(form)
        
        password = CustomUser.objects.make_random_password()
        CustomUser.objects.create_user(username=email, email=email, password=password, is_faculty=True, approved=True)

        # Set the user for the staff object
        staff = form.save(commit=False)
        staff.user = self.request.user
        staff.temp_password = password
        staff.save()

        return super().form_valid(form)

class StaffUpdateView(SuccessMessageMixin, UpdateView):
    model = Staff
    fields = ['current_status', 'first_name', 'last_name', 'gender', 'date_of_birth', 'email', 'mobile_number', 'address', 'comments', 'passport']
    success_message = "Record successfully updated."

    def get_form(self):
        """add date picker in forms"""
        form = super(StaffUpdateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 1})
        form.fields["comments"].widget = widgets.Textarea(attrs={"rows": 1})
        return form

    def form_valid(self, form):
        # Get the old Staff object
        old_staff = self.get_object()

        # Check if email has changed
        old_email = old_staff.email
        new_email = form.cleaned_data['email']
        if old_email != new_email:
                    # Check if the username (email) already exists
            if CustomUser.objects.filter(username=new_email).exists():
                messages.error(self.request, 'This email already exists. Please check if the staff details were not removed by their previous employer.')
                return self.form_invalid(form)
            # Update email in related CustomUser object
            related_user = CustomUser.objects.get(username=old_email)
            related_user.username = new_email
            related_user.email = new_email
            related_user.save()

        return super().form_valid(form)

class StaffDeleteView(DeleteView):
    model = Staff
    success_url = reverse_lazy("staff-list")

    def form_valid(self, form):
        # Get the related CustomUser object
        related_user = CustomUser.objects.get(email=self.object.email)

        # Delete the related CustomUser object
        related_user.delete()

        messages.success(self.request, "Staff successfully deleted.")
        return super().form_valid(form)

apps/staffs/templates/staffs/staff_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this staff will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

apps/staffs/templates/staffs/staff_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool" onclick="printData()">Print</a>
    <a href="{% url 'staff-update' object.pk %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'staff-delete' object.pk %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
<div class="row mb-4">
  <div class="col-sm-4">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'corecode/form_snippet.html' %}
          <input id="passport-input" type="file" name="passport" style="display: none;">
        {% if object.passport %}
          <img id="passport-image" src="{{ object.passport.url }}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
        {% else %}
          {% if object.gender == "female" %}
            <img id="passport-image-gender1" src="{% static 'dist/img/avatar3.png' %}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% else %}
            <img id="passport-image-gender2" src="{% static 'dist/img/avatar5.png' %}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% endif %}
        {% endif %}
      </form>
    <div>
      <h3>{{ object }}</h3>
      <h5>{{ object.get_gender_display }}</h5>
      <h5>{{ object.get_current_status_display }}</h5>
    </div>
  </div>
  <div class="col-sm-8">
    <div>
      <div class="form-group border-bottom row">
        <label class="col">
          Date of Birth
        </label>
        <div class="col">
          {{ object.date_of_birth }}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Mobile Number
        </label>
        <div class="col">
          {{ object.mobile_number}}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Email
        </label>
        <div class="col">
          {{ object.email}}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Address
        </label>
        <div class="col">
          {{ object.address }}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Comments
        </label>
        <div class="col">
          {{ object.comments }}
        </div>
      </div>
      <div class="form-group border-bottom row">
        <label class="col">
          Temporary Password
        </label>
        <div class="col">
          {{ object.temp_password }}
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  // Function to print the content
  function printData() {
    window.print();
  }
</script>
{% endblock content %}

apps/staffs/templates/staffs/staff_form.html
{% extends 'base.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new faculty
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new faculty">
  {% endif %}
</form>


{% endblock content %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    $("#id_mobile_number").on("input", function() {
        var maxLength = 10;
        if ($(this).val().length > maxLength) {
            $(this).val($(this).val().slice(0, maxLength));
        }
    });
});

</script>

apps/staffs/templates/staffs/staff_list.html
{% extends 'base.html' %}

{% block title %}Staffs{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'staff-create' %}"><i
    class="fas fa-plus"></i> New staff</a>
{% endblock breadcrumb %}

{% block content %}
<div class="table-responsive">
  <table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0"
  width="100%">
    <thead>
      <tr>
        <th class="th-sm">S/N</th>
        <th class="th-sm">Fullname</th>
        <th class="th-sm">Gender</th>
        <th class="th-sm">Mobile Phone Number</th>
        <th class="th-sm">Status</th>
      </tr>
    </thead>
    <tbody>

      {% for staff in object_list %}
        <tr class='clickable-row' data-href="{% url 'staff-detail' staff.pk %}">
          <td>{{ forloop.counter}}</td>
          <td>{{ staff.first_name}} {{staff.last_name }}</td>
          <td>{{ staff.get_gender_display}}</td>
          <td>{{ staff.mobile_number}}</td>
          <td>{{ staff.get_current_status_display}}</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
{% endblock content %}


{% block morejs %}
<script>
   $('#stafftable').DataTable({
    select: false
    });
    $(document).ready(function () {
  $('#dtDynamicVerticalScrollExample').DataTable({
    "scrollY": "50vh",
    "scrollCollapse": true,
  });
  $('.dataTables_length').addClass('bs-select');
});
</script>

{% endblock morejs %}

apps/staffs/templates/staffs/staff_upload.html
{% extends 'base.html' %}


{% block title %}
  Upload Bulk Staff from file
{% endblock title %}


{% block content %}

  <div class="col alert alert-info">
    <h5>Instruction</h5>
    <p>Please <a href="{% url 'staff-download-csv' %}">download the CSV file attached here</a>. Fill in the sheet and upload the same file back to this page. DO NOT EDIT THE FIRST ROW</p>
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'corecode/form_snippet.html' %}

    <input type="submit" class="btn btn-success" value="Submit">
  </form>

{% endblock content %}