apps/corecode/urls.py
from django.urls import path

from .views import (
    ClassCreateView,
    ClassDeleteView,
    ClassListView,
    ClassUpdateView,
    CurrentSessionAndTermView,
    IndexView,
    SessionCreateView,
    SessionDeleteView,
    SessionListView,
    SessionUpdateView,
    SiteConfigView,
    FacultyProfileView,
    SubjectCreateView,
    SubjectDeleteView,
    SubjectListView,
    SubjectUpdateView,
    TermCreateView,
    TermDeleteView,
    TermListView,
    TermUpdateView,
    CalendarListView,
    CalendarCreateView,
    CalendarUpdateView,
    CalendarDeleteView,
    DriversView,
    DriverDetailView,
    DriverUpdateView,
    DriverDeleteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("site-config", SiteConfigView.as_view(), name="configs"),
    path("faculty-profile", FacultyProfileView.as_view(), name="faculty-profile"),
    path(
        "current-session/", CurrentSessionAndTermView.as_view(), name="current-session"
    ),
    path("session/list/", SessionListView.as_view(), name="sessions"),
    path("session/create/", SessionCreateView.as_view(), name="session-create"),
    path(
        "session/<int:pk>/update/",
        SessionUpdateView.as_view(),
        name="session-update",
    ),
    path(
        "session/<int:pk>/delete/",
        SessionDeleteView.as_view(),
        name="session-delete",
    ),
    path("term/list/", TermListView.as_view(), name="terms"),
    path("term/create/", TermCreateView.as_view(), name="term-create"),
    path("term/<int:pk>/update/", TermUpdateView.as_view(), name="term-update"),
    path("term/<int:pk>/delete/", TermDeleteView.as_view(), name="term-delete"),
    path("class/list/", ClassListView.as_view(), name="classes"),
    path("class/create/", ClassCreateView.as_view(), name="class-create"),
    path("class/<int:pk>/update/", ClassUpdateView.as_view(), name="class-update"),
    path("class/<int:pk>/delete/", ClassDeleteView.as_view(), name="class-delete"),
    path("subject/list/", SubjectListView.as_view(), name="subjects"),
    path("subject/create/", SubjectCreateView.as_view(), name="subject-create"),
    path(
        "subject/<int:pk>/update/",
        SubjectUpdateView.as_view(),
        name="subject-update",
    ),
    path(
        "subject/<int:pk>/delete/",
        SubjectDeleteView.as_view(),
        name="subject-delete",
    ),
    path("calendar/list/", CalendarListView.as_view(), name="calendar-list"),
    path("calendar/create/", CalendarCreateView.as_view(), name="calendar-create"),
    path("calendar/<int:pk>/update/", CalendarUpdateView.as_view(), name="calendar-update"),
    path('calendar/<int:pk>/delete/', CalendarDeleteView.as_view(), name='calendar-delete'),

    path('drivers/view/', DriversView.as_view(), name='drivers-view'),
    path('drivers/<str:pk>/', DriverDetailView.as_view(), name='driver-details'),
    path("drivers/<str:pk>/update/", DriverUpdateView.as_view(), name="driver-update"),
    path("drivers/delete/<str:pk>/", DriverDeleteView.as_view(), name="driver-delete"),
]

school_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

admin.site.site_header = 'SchooBee Admin Panel'
admin.site.site_title = 'SchooBee'
admin.site.index_title = 'Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("apps.base.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
    path("api/", include("apps.api.urls")),
    path("attendance/", include("apps.attendance.urls")),
    path('timetable/', include('apps.time_table.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.base.views.error_404_view'

apps/base/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import random

class CustomUser(AbstractUser):
    # Common fields for all types of users
    register_id = models.PositiveIntegerField(unique=True)
    email = models.EmailField()
    is_faculty = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Generate a random 5-10 digit number for the register_id field
        while not self.register_id:
            random_id = random.randint(10000, 2147483647)
            if not CustomUser.objects.filter(register_id=random_id).exists():
                self.register_id = random_id

        super().save(*args, **kwargs)

class UserProfile(models.Model):
    COUNTRY_CHOICES = (
        ('IN', 'India (+91)'),
        ('US', 'United States (+1)'),
        ('CA', 'Canada (+1)'),
        ('MX', 'Mexico (+52)'),
        ('GB', 'United Kingdom (+44)'),
        ('FR', 'France (+33)'),
        ('DE', 'Germany (+49)'),
        ('JP', 'Japan (+81)'),
        ('CN', 'China (+86)'),
        ('AU', 'Australia (+61)'),
    )
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='user/profile_pictures/', null=True, blank=True)
    # Fields specific to schools
    mobile_number = models.CharField(max_length=15)
    address = models.CharField(max_length=100)
    country = models.CharField(max_length=2, choices=COUNTRY_CHOICES)
    school_name = models.CharField(max_length=50, blank=True, null=True)
    # school_type = models.CharField(max_length=10, choices=SCHOOL_CHOICES, blank=True, null=True)
    chairman = models.CharField(max_length=50, blank=True, null=True)
    principal = models.CharField(max_length=50, blank=True, null=True)
    supporting_documents = models.FileField(upload_to='user/supporting_documents/', null=True, blank=True)
    # Additional fields that are specific to certain user types go here

apps/corecode/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth import get_user_model
import random
import string

CustomUser = get_user_model()

class SiteConfig(models.Model):
    """Site Configurations"""

    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    key = models.SlugField()
    value = models.CharField(max_length=200)

    def __str__(self):
        return self.key

class AcademicSession(models.Model):
    """Academic Session"""

    def get_academic_year():
        current_year = datetime.now().year
        if datetime.now().month < 8:
            # If current month is less than August, then academic year is previous year - current year
            return f"{current_year - 1}-{current_year}"
        else:
            # If current month is greater than or equal to August, then academic year is current year - next year
            return f"{current_year}-{current_year + 1}"
    default_name = get_academic_year()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default=default_name)
    current = models.BooleanField(default=True)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

class AcademicTerm(models.Model):
    """Academic Term"""

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default="1st Term")
    current = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Subject(models.Model):
    """Subject"""

    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    name = models.CharField(max_length=200, default="Telugu")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

class StudentClass(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default="8th")

    class Meta:
        verbose_name = "Class"
        verbose_name_plural = "Classes"
        ordering = ["name"]
        unique_together = [["user", "name"]]

    def __str__(self):
        return self.name

class Calendar(models.Model):
    EVENT_TYPE = 'event'
    HOLIDAY_TYPE = 'holiday'
    TYPE_CHOICES = [
        (EVENT_TYPE, 'Event'),
        (HOLIDAY_TYPE, 'Holiday'),
    ]
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    date = models.DateField(default=datetime.now)
    type = models.CharField(max_length=7, choices=TYPE_CHOICES)

class Driver(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    id = models.CharField(max_length=9, unique=True, primary_key=True, editable=False)
    is_driveradmin = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)
    alternate_number = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.TextField()
    aadhaar_number = models.CharField(max_length=12, unique=True)
    license_number = models.CharField(max_length=20)
    vehicle_name = models.CharField(max_length=50)
    vehicle_model = models.CharField(max_length=50)
    vehicle_number = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    latitude = models.CharField(max_length=200, null=True, blank=True)
    longitude = models.CharField(max_length=200, null=True, blank=True)

    def save(self, *args, **kwargs):
        # Generate a random 5-10 digit number for the id field
        while not self.id:
            random_id = ''.join(random.choices(string.ascii_uppercase + string.digits, k=9))
            if not Driver.objects.filter(id=random_id).exists():
                self.id = random_id

        super().save(*args, **kwargs)

class Route(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    assigned_driver = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class RouteNode(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    area = models.CharField(max_length=100)
    latitude = models.CharField(max_length=200)
    longitude = models.CharField(max_length=200)
    is_start_stop = models.BooleanField(default=False)
    is_destination_stop = models.BooleanField(default=False)

    def __str__(self):
        return self.area

apps/staffs/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model

CustomUser = get_user_model()

class Staff(models.Model):
    STATUS_CHOICES = [("active", "Active"), ("inactive", "Inactive")]

    GENDER_CHOICES = [("male", "Male"), ("female", "Female")]

    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    email = models.EmailField()
    temp_password = models.CharField(max_length=200)
    current_status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="active")
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default="male")
    date_of_birth = models.DateField(default=timezone.now)

    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13
    )

    address = models.TextField()
    comments = models.TextField(blank=True)
    passport = models.ImageField(blank=True, upload_to="staff/passports/")

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("staff-detail", kwargs={"pk": self.pk})

apps/corecode/templates/corecode/calendar_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Calendar
{% endblock title %}

{% block breadcrumb %}
    <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal1">
        <i class="fa fa-plus"></i>
        Add new record
    </a>
{% endblock breadcrumb %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h2>Events</h2>
            <table class="table table-bordered">
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>{{ object.title }} ({{ object.date }})</td>
                            {% if not user.is_faculty %}
                            <td>
                                <a href="{% url 'calendar-update' object.id %}">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="{% url 'calendar-delete' object.id %}">
                                    <i class="fa fa-trash-alt"></i>
                                </a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-sm-6">
            <h2>Holidays</h2>
            <table class="table table-bordered">
                <tbody>
                    {% for holiday in holidays %}
                        <tr>
                            <td>{{ holiday.title }} ({{ holiday.date }})</td>
                            {% if not user.is_faculty %}
                            <td>
                                <a href="{% url 'calendar-update' holiday.id %}">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="{% url 'calendar-delete' holiday.id %}">
                                    <i class="fa fa-trash-alt"></i>
                                </a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="{% url 'calendar-create' %}" method="POST">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add new record</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group">
                                {{field.label_tag}}
                                {{ field|add_class:"form-control" }}
                            </div>
                        {% endfor %}
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

apps/corecode/templates/corecode/class_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Classes
{% endblock title %}


{% block breadcrumb %}
  <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal1">
    <i class="fa fa-plus"></i>
    Add new class
  </a>
{% endblock breadcrumb %}
  

{% block content %}
{% if object in object_list %}
              Worls
            {% endif %}
  <div class="row">
    <div class="col-sm-12">

        <table class="table table-bordered">
          <tbody>
            
            {% for object in object_list %}
            <tr>
              <td>{{ object }}</td>
              <td><a href="{% url 'class-update' object.pk %}"><i
                    class="fa fa-edit"></i></a> <a
                  href="{% url 'class-delete' object.pk %}"><i
                    class="fa fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
            
          </tbody>
        </table>

    </div>
  </div>


  <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'class-create' %}" method="POST">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add new class</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              {% csrf_token %}

              {% for field in form %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{ field|add_class:"form-control" }}
                    {{field.help_text}}
                    {{field.errors}}
                  </div>
              {% endfor %}
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

apps/corecode/templates/corecode/core_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<span class="card-title"><strong>{{ object}}</strong> about to be
  deleted!</span>
{% endblock title %}


{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-body">
          <p>Are you sure you want to delete object <strong>{{ object}}</strong>
            alongside all attached contents?</p>
          <div class="mt-2 red-text">This action cannot be undone</div>

          <form method="POST" class="mt-3">
            {% csrf_token %}

            <button type="submit" class="btn btn-primary">
              Confirm Delete
              <i class="fa fa-trash-alt"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

apps/corecode/templates/corecode/driver_form.html
{% extends 'base.html' %}


{% block title %}

  {% if object %}
    Update Driver {{ object.id }}
  {% else %}
    Add new driver
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new driver">
  {% endif %}
</form>


{% endblock content %}


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    $("#id_phone_number").on("input", function() {
        var maxLength = 10;
        if ($(this).val().length > maxLength) {
            $(this).val($(this).val().slice(0, maxLength));
        }
    });
});
$(document).ready(function() {
    $("#id_alternate_number").on("input", function() {
        var maxLength = 10;
        if ($(this).val().length > maxLength) {
            $(this).val($(this).val().slice(0, maxLength));
        }
    });
});

</script>

apps/corecode/templates/corecode/drivers.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
Drivers
{% endblock title %}

{% block content %}

<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-6">
      <h2>Drivers</h2>
      <table id="drivertable" class="table table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>Name</th>
            <th>Phone Number</th>
          </tr>
        </thead>
        <tbody>
          {% for driver in drivers %}
          <tr class='clickable-row' data-href="{% url 'driver-details' driver.id %}">
            <td>{{ driver.name }}</td>
            <td>{{ driver.phone_number }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="col-md-6">
      <h2>Add Driver</h2>
      <form method="POST">
        {% csrf_token %}
        {% for field in driver_form %}
        {% if field.name == 'is_driveradmin' %}
        <div class="form-group d-flex" style="flex-direction: row; justify-content: start; align-items: center;">
          <input type="checkbox" name="is_driveradmin" class="form-control" id="id_is_driveradmin" style="width: 20px;">
          <label for="id_is_driveradmin" style="margin-left: 10px; margin-bottom: 0;">Transport Manager</label>
        </div>
        {% else %}
        <div class="form-group">
          {{ field.label_tag }}
          {% render_field field class="form-control" %}
          {{ field.help_text }}
          {% if field.errors %}
          {% for error in field.errors %}
          <div class="invalid-feedback d-block">
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>
        {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

{% block morejs %}
<script>
  $('#drivertable').DataTable({
  });
</script>

{% endblock morejs %}

apps/corecode/templates/corecode/facultyprofile.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="col-sm-12">
    <div class="col-sm-4">
      {% include 'corecode/form_snippet.html' %}
        {% if staff_url %}
          <img id="passport-image" src="{{ staff_url }}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;margin-top: 2rem;">
        {% else %}
          {% if staff_profile_form.gender.value == "female" %}
            <img id="passport-image-gender1" src="{% static 'dist/img/avatar3.png' %}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;margin-top: 2rem;">
          {% else %}
            <img id="passport-image-gender2" src="{% static 'dist/img/avatar5.png' %}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;margin-top: 2rem;">
          {% endif %}
        {% endif %}
      </div>
    </div>
    <br>
    <div class="col-sm-12">
      <div>
        <input type="hidden" name="register_id" value="{{ custom_user_form.instance.register_id }}">

        <div class="form-group d-flex">
          <div class="flex-grow-1 mr-2">
            <label for="{{ staff_profile_form.first_name.id_for_label }}">First Name:</label>
            {{ staff_profile_form.first_name|add_class:"form-control"|attr:"placeholder: Enter your chairman name" }}
          </div>

          <div class="flex-grow-1">
            <label for="{{ staff_profile_form.last_name.id_for_label }}">Last Name:</label>
            {{ staff_profile_form.last_name|add_class:"form-control"|attr:"placeholder: Enter your principal name" }}
          </div>
        </div>

        <div class="form-group d-flex">
          <div class="flex-grow-1 mr-2">
            <label for="{{ custom_user_form.email.id_for_label }}">Email:</label>
            {{ custom_user_form.email|add_class:"form-control"|attr:"placeholder: Enter your email"|attr:"type: email" }}
          </div>

          <div class="flex-grow-1 mr-2">
            <label for="{{ staff_profile_form.mobile_number.id_for_label }}">Mobile Number:</label>
            {{ staff_profile_form.mobile_number|add_class:"form-control"|attr:"placeholder: Enter your mobile number" }}
          </div>

          <div class="flex-grow-1">
            <label for="{{ staff_profile_form.gender.id_for_label }}">Gender:</label>
            {{ staff_profile_form.gender|add_class:"form-control"|attr:"placeholder: Select gender" }}
          </div>
        </div>

        <div class="form-group d-flex">
          <div class="flex-grow-1 mr-2" style="width: 70%">
            <label for="{{ staff_profile_form.address.id_for_label }}">Address:</label>
            {{ staff_profile_form.address|add_class:"form-control"|attr:"placeholder: Select gender" }}
          </div>

          <div class="flex-grow-1" style="width: 30%">
            <label for="{{ staff_profile_form.date_of_birth.id_for_label }}">Date of Birth:</label>
            {{ staff_profile_form.date_of_birth|add_class:"form-control"|attr:"placeholder: Enter your date of birth" }}
          </div>
        </div>
        <div style="margin-bottom: 20px;">
          <label for="{{ staff_profile_form.passport.id_for_label }}">Passport:</label><br>
          <input type="file" name="passport" accept="image/*" id="id_passport">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <p style="margin-top: 15px;margin-bottom: 0;"><a href="{% url 'change_password' %}"> Click here</a> To Change the Password</p>
      </div>
    </div>
  </div>
</form>
{% endblock content %}

apps/corecode/templates/corecode/siteconfig.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-sm-12">
      <div style="text-align: center;">
        {% include 'corecode/form_snippet.html' %}
          {% if user_url %}
            <img id="passport-image" src="{{ user_url }}" class="rounded-circle mr-3" style="width: 120px; height: 120px;margin-top: 2rem;">
          {% else %}
            <img id="passport-image-gender2" src="{% static 'dist/img/school3.png' %}" class="rounded-circle mr-3" style="width: 120px; height: 120px;margin-top: 2rem;">
          {% endif %}
        </div>
      </div>
      <br>
    <div class="form-group">
      <label>Register ID:</label>
      <span class="form-control-static">{{ custom_user_form.register_id.value }}</span>
    </div>   

    <input type="hidden" name="register_id" value="{{ custom_user_form.instance.register_id }}">
    <div class="form-group">
      <label for="{{ user_profile_form.school_name.id_for_label }}">School Name:</label>
      {{ user_profile_form.school_name|add_class:"form-control"|attr:"placeholder: Enter your school name" }}
    </div>

    <div class="form-group d-flex">
      <div class="flex-grow-1 mr-2">
        <label for="{{ user_profile_form.chairman.id_for_label }}">Chairman:</label>
        {{ user_profile_form.chairman|add_class:"form-control"|attr:"placeholder: Enter your chairman name" }}
      </div>

      <div class="flex-grow-1">
        <label for="{{ user_profile_form.principal.id_for_label }}">Principal:</label>
        {{ user_profile_form.principal|add_class:"form-control"|attr:"placeholder: Enter your principal name" }}
      </div>
    </div>

    <div class="form-group d-flex">
      <div class="flex-grow-1 mr-2">
        <label for="{{ custom_user_form.email.id_for_label }}">Email:</label>
        {{ custom_user_form.email|add_class:"form-control"|attr:"placeholder: Enter your email"|attr:"type: email" }}
      </div>
  
      <div class="flex-grow-1">
        <label for="{{ user_profile_form.mobile_number.id_for_label }}">Mobile Number:</label>
        {{ user_profile_form.mobile_number|add_class:"form-control"|attr:"placeholder: Enter your mobile number" }}
      </div>
    </div>

    <div class="form-group d-flex">
      <div class="flex-grow-1 mr-2" style="width: 70%">
        <label for="{{ user_profile_form.address.id_for_label }}">Address:</label>
        {{ user_profile_form.address|add_class:"form-control"|attr:"placeholder: Enter your address" }}
      </div>
    
      <div class="flex-grow-1" style="width: 30%">
        <label for="{{ user_profile_form.country.id_for_label }}">Country:</label>
        {{ user_profile_form.country|add_class:"form-control"|attr:"placeholder: Enter your country" }}
      </div>
    </div>
    <div style="margin-bottom: 20px;">
      <label for="{{ user_profile_form.profile_picture.id_for_label }}">Passport:</label><br>
      <input type="file" name="profile_picture" accept="image/*" id="id_profile_picture">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

    <p style="margin-top: 15px;margin-bottom: 0;"><a href="{% url 'change_password' %}"> Click here</a> To Change the Password</p>
  </form>
{% endblock content %}